# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nuefs.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "DaemonInfo",
    "DaemonInfoReq",
    "Empty",
    "ManifestEntry",
    "MountReq",
    "MountRoot",
    "MountStatus",
    "OkPayload",
    "OwnerInfo",
    "Request",
    "ResolveReq",
    "ResolveResult",
    "Response",
    "ShutdownReq",
    "StatusList",
    "StatusReq",
    "UnmountReq",
    "UpdateReq",
    "WhichReq",
)

from dataclasses import dataclass

import betterproto2

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class DaemonInfo(betterproto2.Message):
    pid: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    socket: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    started_at: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)


default_message_pool.register_message("nuefs", "DaemonInfo", DaemonInfo)


@dataclass(eq=False, repr=False)
class DaemonInfoReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "DaemonInfoReq", DaemonInfoReq)


@dataclass(eq=False, repr=False)
class Empty(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "Empty", Empty)


@dataclass(eq=False, repr=False)
class ManifestEntry(betterproto2.Message):
    """
    -- Data types --
    """

    virtual_path: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    is_dir: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("nuefs", "ManifestEntry", ManifestEntry)


@dataclass(eq=False, repr=False)
class MountReq(betterproto2.Message):
    root: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    entries: "list[ManifestEntry]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    mount_roots: "list[MountRoot]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "MountReq", MountReq)


@dataclass(eq=False, repr=False)
class MountRoot(betterproto2.Message):
    virtual_prefix: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "MountRoot", MountRoot)


@dataclass(eq=False, repr=False)
class MountStatus(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    root: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "MountStatus", MountStatus)


@dataclass(eq=False, repr=False)
class OkPayload(betterproto2.Message):
    """


    Oneofs:
        - value:
    """

    mount_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_UINT64, optional=True, group="value"
    )

    owner_info: "OwnerInfo | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="value"
    )

    status: "StatusList | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="value"
    )

    daemon_info: "DaemonInfo | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="value"
    )

    resolve: "ResolveResult | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="value"
    )

    empty: "Empty | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="value"
    )


default_message_pool.register_message("nuefs", "OkPayload", OkPayload)


@dataclass(eq=False, repr=False)
class OwnerInfo(betterproto2.Message):
    owner: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "OwnerInfo", OwnerInfo)


@dataclass(eq=False, repr=False)
class Request(betterproto2.Message):
    """
    -- Requests --

    Oneofs:
        - method:
    """

    mount: "MountReq | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    unmount: "UnmountReq | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    which: "WhichReq | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    status: "StatusReq | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    daemon_info: "DaemonInfoReq | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    update: "UpdateReq | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    resolve: "ResolveReq | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )

    shutdown: "ShutdownReq | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True, group="method"
    )


default_message_pool.register_message("nuefs", "Request", Request)


@dataclass(eq=False, repr=False)
class ResolveReq(betterproto2.Message):
    root: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "ResolveReq", ResolveReq)


@dataclass(eq=False, repr=False)
class ResolveResult(betterproto2.Message):
    mount_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_UINT64, optional=True
    )


default_message_pool.register_message("nuefs", "ResolveResult", ResolveResult)


@dataclass(eq=False, repr=False)
class Response(betterproto2.Message):
    """
    -- Responses --

    Oneofs:
        - result:
    """

    ok: "OkPayload | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True, group="result"
    )

    error: "str | None" = betterproto2.field(
        2, betterproto2.TYPE_STRING, optional=True, group="result"
    )


default_message_pool.register_message("nuefs", "Response", Response)


@dataclass(eq=False, repr=False)
class ShutdownReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "ShutdownReq", ShutdownReq)


@dataclass(eq=False, repr=False)
class StatusList(betterproto2.Message):
    mounts: "list[MountStatus]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "StatusList", StatusList)


@dataclass(eq=False, repr=False)
class StatusReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "StatusReq", StatusReq)


@dataclass(eq=False, repr=False)
class UnmountReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


default_message_pool.register_message("nuefs", "UnmountReq", UnmountReq)


@dataclass(eq=False, repr=False)
class UpdateReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    entries: "list[ManifestEntry]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    mount_roots: "list[MountRoot]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "UpdateReq", UpdateReq)


@dataclass(eq=False, repr=False)
class WhichReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "WhichReq", WhichReq)
