# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nuefs.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "DaemonInfo",
    "DaemonInfoReq",
    "DaemonInfoResp",
    "ManifestEntry",
    "MountReq",
    "MountResp",
    "MountRoot",
    "MountStatus",
    "NueFsStub",
    "OwnerInfo",
    "ResolveReq",
    "ResolveResp",
    "ShutdownReq",
    "ShutdownResp",
    "StatusReq",
    "StatusResp",
    "UnmountReq",
    "UnmountResp",
    "UpdateReq",
    "UpdateResp",
    "WhichReq",
    "WhichResp",
)

from dataclasses import dataclass

import betterproto2
import grpc

from ..message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class DaemonInfo(betterproto2.Message):
    pid: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    socket: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    started_at: "int" = betterproto2.field(3, betterproto2.TYPE_UINT64)


default_message_pool.register_message("nuefs", "DaemonInfo", DaemonInfo)


@dataclass(eq=False, repr=False)
class DaemonInfoReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "DaemonInfoReq", DaemonInfoReq)


@dataclass(eq=False, repr=False)
class DaemonInfoResp(betterproto2.Message):
    info: "DaemonInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("nuefs", "DaemonInfoResp", DaemonInfoResp)


@dataclass(eq=False, repr=False)
class ManifestEntry(betterproto2.Message):
    """
    -- Data types --
    """

    virtual_path: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    is_dir: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message("nuefs", "ManifestEntry", ManifestEntry)


@dataclass(eq=False, repr=False)
class MountReq(betterproto2.Message):
    """
    -- Requests --
    """

    root: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    entries: "list[ManifestEntry]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    mount_roots: "list[MountRoot]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "MountReq", MountReq)


@dataclass(eq=False, repr=False)
class MountResp(betterproto2.Message):
    """
    -- Responses --
    """

    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


default_message_pool.register_message("nuefs", "MountResp", MountResp)


@dataclass(eq=False, repr=False)
class MountRoot(betterproto2.Message):
    virtual_prefix: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "MountRoot", MountRoot)


@dataclass(eq=False, repr=False)
class MountStatus(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    root: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "MountStatus", MountStatus)


@dataclass(eq=False, repr=False)
class OwnerInfo(betterproto2.Message):
    owner: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    backend_path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "OwnerInfo", OwnerInfo)


@dataclass(eq=False, repr=False)
class ResolveReq(betterproto2.Message):
    root: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "ResolveReq", ResolveReq)


@dataclass(eq=False, repr=False)
class ResolveResp(betterproto2.Message):
    mount_id: "int | None" = betterproto2.field(
        1, betterproto2.TYPE_UINT64, optional=True
    )


default_message_pool.register_message("nuefs", "ResolveResp", ResolveResp)


@dataclass(eq=False, repr=False)
class ShutdownReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "ShutdownReq", ShutdownReq)


@dataclass(eq=False, repr=False)
class ShutdownResp(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "ShutdownResp", ShutdownResp)


@dataclass(eq=False, repr=False)
class StatusReq(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "StatusReq", StatusReq)


@dataclass(eq=False, repr=False)
class StatusResp(betterproto2.Message):
    mounts: "list[MountStatus]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "StatusResp", StatusResp)


@dataclass(eq=False, repr=False)
class UnmountReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)


default_message_pool.register_message("nuefs", "UnmountReq", UnmountReq)


@dataclass(eq=False, repr=False)
class UnmountResp(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "UnmountResp", UnmountResp)


@dataclass(eq=False, repr=False)
class UpdateReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    entries: "list[ManifestEntry]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    mount_roots: "list[MountRoot]" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message("nuefs", "UpdateReq", UpdateReq)


@dataclass(eq=False, repr=False)
class UpdateResp(betterproto2.Message):
    pass


default_message_pool.register_message("nuefs", "UpdateResp", UpdateResp)


@dataclass(eq=False, repr=False)
class WhichReq(betterproto2.Message):
    mount_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)

    path: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("nuefs", "WhichReq", WhichReq)


@dataclass(eq=False, repr=False)
class WhichResp(betterproto2.Message):
    owner_info: "OwnerInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("nuefs", "WhichResp", WhichResp)


class NueFsStub:
    """
    -- Service --
    """

    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def mount(self, message: "MountReq") -> "MountResp":
        return self._channel.unary_unary(
            "/nuefs.NueFs/Mount",
            MountReq.SerializeToString,
            MountResp.FromString,
        )(message)

    def unmount(self, message: "UnmountReq") -> "UnmountResp":
        return self._channel.unary_unary(
            "/nuefs.NueFs/Unmount",
            UnmountReq.SerializeToString,
            UnmountResp.FromString,
        )(message)

    def which(self, message: "WhichReq") -> "WhichResp":
        return self._channel.unary_unary(
            "/nuefs.NueFs/Which",
            WhichReq.SerializeToString,
            WhichResp.FromString,
        )(message)

    def status(self, message: "StatusReq | None" = None) -> "StatusResp":
        if message is None:
            message = StatusReq()

        return self._channel.unary_unary(
            "/nuefs.NueFs/Status",
            StatusReq.SerializeToString,
            StatusResp.FromString,
        )(message)

    def get_daemon_info(
        self, message: "DaemonInfoReq | None" = None
    ) -> "DaemonInfoResp":
        if message is None:
            message = DaemonInfoReq()

        return self._channel.unary_unary(
            "/nuefs.NueFs/GetDaemonInfo",
            DaemonInfoReq.SerializeToString,
            DaemonInfoResp.FromString,
        )(message)

    def update(self, message: "UpdateReq") -> "UpdateResp":
        return self._channel.unary_unary(
            "/nuefs.NueFs/Update",
            UpdateReq.SerializeToString,
            UpdateResp.FromString,
        )(message)

    def resolve(self, message: "ResolveReq") -> "ResolveResp":
        return self._channel.unary_unary(
            "/nuefs.NueFs/Resolve",
            ResolveReq.SerializeToString,
            ResolveResp.FromString,
        )(message)

    def shutdown(self, message: "ShutdownReq | None" = None) -> "ShutdownResp":
        if message is None:
            message = ShutdownReq()

        return self._channel.unary_unary(
            "/nuefs.NueFs/Shutdown",
            ShutdownReq.SerializeToString,
            ShutdownResp.FromString,
        )(message)
