[workspace]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "nuefs"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "nuefs"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-rattler-build"
version = "*"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]
check = "cargo check"
kill = "pkill -9 nuefsd || true"
stop = "nue stop 2>/dev/null || pkill -9 nuefsd || true"
test = "pytest tests -v"
bench = "python -m tests.bench_fio"
posixtest = "python -m uposixtest"

[dependencies]
nuefs = { path = "." }
pytest = "*"
rust = "*"
python = "=3.12"
humanize = "*"
packageurl-python = "*"
universal-pathlib = "*"

[pypi-dependencies]
uposixtest = { path = "uposixtest", editable = true }
