[package]
name = "nuefs_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "nuefs_rs"

[[bin]]
name = "nuefsd"

[dependencies]
camino = { version = "1", features = ["serde1"] }
prost = "0.14"
tonic = "0.14"
tonic-prost = "0.14"
tokio-stream = { version = "0.1", features = ["net"] }
serde = { version = "1", features = ["derive"] }
fuser = "0.16"
libc = "0.2"
rustix = { version = "1", features = ["fs", "process"] }
thiserror = "2"
parking_lot = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
