package:
  name: nuefsd
  version: 0.1.0

source:
  path: ..
  use_gitignore: true

build:
  number: 0
  script: |
    cargo install --locked --root "$PREFIX" --path . --bin nuefsd \
      --target-dir target --no-track --force

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - protobuf
  host:
    - libfuse3
  run: []

tests:
  - script:
      - nuefsd --help
