// @generated
// This file is @generated by prost-build.
// -- Data types --

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestEntry {
    #[prost(string, tag = "1")]
    pub virtual_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub backend_path: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_dir: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MountRoot {
    #[prost(string, tag = "1")]
    pub virtual_prefix: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub backend_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OwnerInfo {
    #[prost(string, tag = "1")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub backend_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MountStatus {
    #[prost(uint64, tag = "1")]
    pub mount_id: u64,
    #[prost(string, tag = "2")]
    pub root: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DaemonInfo {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(string, tag = "2")]
    pub socket: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub started_at: u64,
}
// -- Requests --

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MountReq {
    #[prost(string, tag = "1")]
    pub root: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<ManifestEntry>,
    #[prost(message, repeated, tag = "3")]
    pub mount_roots: ::prost::alloc::vec::Vec<MountRoot>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnmountReq {
    #[prost(uint64, tag = "1")]
    pub mount_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhichReq {
    #[prost(uint64, tag = "1")]
    pub mount_id: u64,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusReq {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DaemonInfoReq {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateReq {
    #[prost(uint64, tag = "1")]
    pub mount_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<ManifestEntry>,
    #[prost(message, repeated, tag = "3")]
    pub mount_roots: ::prost::alloc::vec::Vec<MountRoot>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveReq {
    #[prost(string, tag = "1")]
    pub root: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShutdownReq {
}
// -- Responses --

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MountResp {
    #[prost(uint64, tag = "1")]
    pub mount_id: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnmountResp {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhichResp {
    #[prost(message, optional, tag = "1")]
    pub owner_info: ::core::option::Option<OwnerInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResp {
    #[prost(message, repeated, tag = "1")]
    pub mounts: ::prost::alloc::vec::Vec<MountStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DaemonInfoResp {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<DaemonInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateResp {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveResp {
    #[prost(uint64, optional, tag = "1")]
    pub mount_id: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShutdownResp {
}
include!("nuefs.tonic.rs");
// @@protoc_insertion_point(module)