# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "DaemonInfo",
    "ManifestEntry",
    "OwnerInfo",
    "RawHandle",
]

@typing.final
class DaemonInfo:
    r"""
    Information about the running daemon.
    """
    @property
    def pid(self) -> builtins.int: ...
    @property
    def socket(self) -> pathlib.Path: ...
    @property
    def started_at(self) -> builtins.int: ...

@typing.final
class ManifestEntry:
    r"""
    Pre-computed manifest entry for IPC.
    """
    @property
    def virtual_path(self) -> builtins.str:
        r"""
        Relative path within mount root.
        """
    @virtual_path.setter
    def virtual_path(self, value: builtins.str) -> None:
        r"""
        Relative path within mount root.
        """
    @property
    def backend_path(self) -> pathlib.Path:
        r"""
        Absolute path to backend file.
        """
    @backend_path.setter
    def backend_path(self, value: pathlib.Path) -> None:
        r"""
        Absolute path to backend file.
        """
    @property
    def is_dir(self) -> builtins.bool:
        r"""
        Whether this entry is a directory.
        """
    @is_dir.setter
    def is_dir(self, value: builtins.bool) -> None:
        r"""
        Whether this entry is a directory.
        """
    def __new__(cls, virtual_path: builtins.str, backend_path: builtins.str | os.PathLike | pathlib.Path, is_dir: builtins.bool) -> ManifestEntry: ...
    @staticmethod
    def _pydantic_validate(v: typing.Any) -> typing.Any: ...
    @staticmethod
    def _pydantic_serialize(v: typing.Any) -> typing.Any: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source: typing.Any, _handler: typing.Any) -> typing.Any: ...

@typing.final
class OwnerInfo:
    r"""
    Information about which backend owns a path.
    """
    @property
    def owner(self) -> builtins.str: ...
    @property
    def backend_path(self) -> pathlib.Path: ...

@typing.final
class RawHandle:
    r"""
    Raw handle data from NueFS daemon.
    """
    @property
    def root(self) -> pathlib.Path: ...
    @property
    def mount_id(self) -> builtins.int: ...

def _daemon_info() -> DaemonInfo:
    r"""
    Get daemon info.
    """

def _mount(root: builtins.str | os.PathLike | pathlib.Path, entries: typing.Sequence[ManifestEntry]) -> RawHandle:
    r"""
    Create a new mount.
    """

def _resolve(root: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.int]:
    r"""
    Resolve an existing mount by root. Returns mount_id if found.
    """

def _status() -> builtins.list[RawHandle]:
    r"""
    List all active mounts.
    """

def _unmount(mount_id: builtins.int) -> None:
    r"""
    Unmount by mount_id.
    """

def _update(mount_id: builtins.int, entries: typing.Sequence[ManifestEntry]) -> None:
    r"""
    Update mount manifest.
    """

def _which(mount_id: builtins.int, path: builtins.str) -> typing.Optional[OwnerInfo]:
    r"""
    Query path owner. Returns None if not found.
    """

