# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib
import typing

class DaemonInfo:
    r"""
    Information about the running daemon.
    """
    pid: builtins.int
    socket: builtins.str
    started_at: builtins.int

class ManifestEntry:
    r"""
    Pre-computed manifest entry for IPC.
    """
    virtual_path: builtins.str
    backend_path: builtins.str
    is_dir: builtins.bool
    def __new__(cls,virtual_path:builtins.str, backend_path:builtins.str | os.PathLike | pathlib.Path, is_dir:builtins.bool): ...
    @staticmethod
    def _pydantic_validate(v:typing.Any) -> typing.Any:
        ...

    @staticmethod
    def _pydantic_serialize(v:typing.Any) -> typing.Any:
        ...

    @classmethod
    def __get_pydantic_core_schema__(cls, cls:type, _source:typing.Any, _handler:typing.Any) -> typing.Any:
        ...


class OwnerInfo:
    r"""
    Information about which backend owns a path.
    """
    owner: builtins.str
    backend_path: builtins.str

class RawHandle:
    r"""
    Raw handle data from NueFS daemon.
    """
    root: builtins.str
    mount_id: builtins.int

def _daemon_info() -> DaemonInfo:
    r"""
    Get daemon info.
    """
    ...

def _mount(root:builtins.str | os.PathLike | pathlib.Path, entries:typing.Sequence[ManifestEntry]) -> RawHandle:
    r"""
    Create a new mount.
    """
    ...

def _resolve(root:builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.int]:
    r"""
    Resolve an existing mount by root. Returns mount_id if found.
    """
    ...

def _status() -> builtins.list[RawHandle]:
    r"""
    List all active mounts.
    """
    ...

def _unmount(mount_id:builtins.int) -> None:
    r"""
    Unmount by mount_id.
    """
    ...

def _update(mount_id:builtins.int, entries:typing.Sequence[ManifestEntry]) -> None:
    r"""
    Update mount manifest.
    """
    ...

def _which(mount_id:builtins.int, path:builtins.str) -> typing.Optional[OwnerInfo]:
    r"""
    Query path owner. Returns None if not found.
    """
    ...

