# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib
import typing

class Mapping:
    r"""
    Single path mapping: source directory -> target path within mount root.
    """
    target: builtins.str
    source: builtins.str
    def __new__(cls,target:builtins.str | os.PathLike | pathlib.Path, source:builtins.str | os.PathLike | pathlib.Path): ...

class MountHandle:
    r"""
    Handle to a mounted NueFS filesystem.
    """
    root: builtins.str
    def is_mounted(self) -> builtins.bool:
        r"""
        Check if the mount is still tracked by the daemon.
        """
        ...


class MountStatus:
    mount_id: builtins.int
    root: builtins.str

class OwnerInfo:
    r"""
    Information about which backend owns a path.
    """
    owner: builtins.str
    backend_path: builtins.str

def get_manifest(handle:MountHandle) -> builtins.list[Mapping]:
    ...

def mount(root:builtins.str | os.PathLike | pathlib.Path, mounts:typing.Sequence[Mapping]) -> MountHandle:
    ...

def status(root:typing.Optional[builtins.str | os.PathLike | pathlib.Path]) -> builtins.list[MountStatus]:
    ...

def unmount(handle:MountHandle) -> None:
    ...

def unmount_root(root:builtins.str | os.PathLike | pathlib.Path) -> None:
    ...

def update(handle:MountHandle, mounts:typing.Sequence[Mapping]) -> None:
    ...

def which(handle:MountHandle, path:builtins.str) -> typing.Optional[OwnerInfo]:
    ...

def which_root(root:builtins.str | os.PathLike | pathlib.Path, path:builtins.str) -> typing.Optional[OwnerInfo]:
    ...

